apiVersion: apisix.apache.org/v1alpha1
kind: PluginConfig
metadata:
  name: oidc-auth
  namespace: {{ .Values.gateway.namespace }}
spec:
  plugins:
    - name: openid-connect
      config:
        client_id: {{ .Values.oidc.clientId }}
        client_secret: {{ .Values.oidc.clientSecret }}
        discovery: {{ .Values.oidc.keycloakUrl }}
        scope: openid
        bearer_only: true
        realm: {{ .Values.oidc.realm }}
