apiVersion: apisix.apache.org/v1alpha1
kind: PluginConfig
metadata:
  name: oidc-auth-full
  namespace: {{ .Values.gateway.namespace }}
spec:
  plugins:
    - name: authz-keycloak
      config:
        token_endpoint: {{ .Values.oidc.tokenEndpoint }}
        permissions:
          - full-access-api
        client_id: {{ .Values.oidc.clientId }}
        client_secret: {{ .Values.oidc.clientSecret }}
        grant_type: "urn:ietf:params:oauth:grant-type:uma-ticket"
        access_denied_status: 403
