---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-push-secret
  namespace: camel-k
spec:
  encryptedData:
    .dockerconfigjson: AgDZb3KwjDMtH3cjw0/kAZ15sxr4+VCiG+K8NW9HE5EdjwKlE9wQ3Zc+MunLkIvs2ai+iiZVAFp/obmigAoI1In/gdZiahhv1VrBysfbIRY7pbCffTKLah/jTmUasoiEqFmiN63vrLGZPQrPx3d9plFH3gnjpGr69ZRSrkbf41qIn8uhc+HLkv6ZAtRGpsSeAJ/X+g/H+l2hrucIc01bKMRjZ3mQf/dN2/JIgydlRHWixc9PxXacl7nrKv4dMe8B7vV8TzNG/YIupySeLCiRZv94GClQfxZlt7+ZNtLb3wZZuJ++VeAHBXRjIKYA9muYk45C05RN+qW6ecKS5opcIXvbiI6w0azNkV9ufcK05UZ+6tVw/D0T0TMcZaZWk/sfanKcQX3wmDFdnT564XS/QXA01SMsFOwH+jAGNCphjhNFRDFx5Cg2JtKXwvw2Y6nxWwirPq+edW/17jL+hG6D/PhjsK2U35uHzNqAYhFSb9WP4z4r3kemTRwHmZCqHIYQaV+fJVNR5x2IRgzofkrs8y7fONxqFtIESE/bTC+bOJ6sd3BpN2UXSCQwZln4QvjHFGNn7TmEMg1m5RZ5V41s9IvKjN8FPW06iDm1bWnQalK1dnQmh8vPlnsl852tCK1J/7JxeSkTOZ5kpEAqE38AM+GrB/hl92USVGsrFy/z6FQlX4A5pfTRK00PyOMJVOlVJ000/WjYZas018Jq1fSR7V1dmdQzdu2EHDsB92c6tu3xoaYT3j9MKAnG9poRs7oDiYJ30awnCxRMsklQnpe265zqdVZDfX1fXBKc8V7XKz7G1Waip1xUnyH3Iyf5xDjwuvK4jjMlOjLtuk/KoOrPgYfLzJJaEFn7on5r0RIRBUofd+eJZStNoZpgp+vK9796YIO5N2XTfuRAOrkq/jJ+8D7GLavjW12oWynXEmQrVRcioQmiePbHGSe/Pdjp8JfKnwE=
  template:
    metadata:
      name: dockerhub-push-secret
      namespace: camel-k
    type: kubernetes.io/dockerconfigjson
