apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: merge-data
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  traits:
    knative-service:
      enabled: false
  sources:
    - name: merge-data.yaml
      language: yaml
      content: |
        - from:
            uri: "platform-http:/foobar"
            steps:
              - setBody:
                  expression:
                    constant: '{"status":"camel-k is working"}'
              - setHeader:
                  name: Content-Type
                  expression:
                    constant: "application/json"
---
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: serverless-data
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  traits:
    knative-service:
      enabled: true
  sources:
    - name: serverless-data.yaml
      language: yaml
      content: |
        - from:
            uri: "platform-http:/"
            steps:
              - setBody:
                  expression:
                    constant: '{"status":"camel-k is working"}'
              - setHeader:
                  name: Content-Type
                  expression:
                    constant: "application/json"
