apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: ref-demo
  namespace: {{ .Values.namespace }}
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: {{ .Values.gateway.namespace }}
  to:
  - group: ""
    kind: Service
