{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - port: 80
      targetPort: {{ .port }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: mergedata
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mergedata
  ports:
    - port: 80
      targetPort: {{ .Values.mergedata.port }}
