---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-credentials
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgAXN751Cwi4Xvt0gy4fUhpGV8vv+kygMme1xKPHSpnzBLtGgl3uvY9aEcGrVsNNQB3iAZs9PRKJnAtSH0C0D47drZ/ZMTEpaqJBrVptwzzm033haqgNYMDuv3RitMxGBe4JDdpyA9UcjdXxbQx1KznSmJGxv0xMF30rQodHVXPeyou0x86sCnlVJRhU8mzXCjGntOeqhupBddo0x+vHuJZ41AkKvUYR3QqWRDzgcOALdnO+nb9bs0y5+YIvm3I+nktmblJMqwSRC4cOfeklPWNfiBnpn/briZeUw1Dx/aYOzOIQSdw9CIUMHAs+6AyfH1J8s0MwDhhOxiwG0GdmojHGk/ff+1f4GUuWOD4WU4InGxuUlhXZlBUog7EOxAKgtJ+9pzssO3WRMCdAElN//6rk7UoD0hzkbxRXXJ2Xc0Wb8gQKa4U8lNxbfFDP+bh6hjGAw80SmB6f/maZd9mBsI2wlGrERnCRTstdAv+CC62Ueo5x6bU/HzR32TFxeAgPDYXOzb4U6MtkU1zsqo8vQqky3Sg1rttMrhHXHLBYf3h6K7jRAIbXRFDHlUIkHKbD8hGtOWHIGh2OVoHlBQ/vqqTnkGvruC/GLtohxtVrn9ecrmE8bfzEk5qSBy4v82LDbToSJOL54r+hR+xEW+fflCJ/87Vy19mEl/8RY4VtXfjyuuf/7aNlfU1kLorlLTPszqd8WQCxJ0246w==
    postgres-password: AgAx5pfkoKdxJJorphYR4KMz3A+LfD7jmWqSVTfCu7fXKCBfLjQ59kCV7fx1WCBFh2bDHY8DiddjXjcHD/4X7qr2kbmt/QD8x+t7U15SvR+J6fE5yIcx0AOSMjQ6neDuQdGOpb0IPzkkhhaw98Vd4WJLq84koDPSsGcPLFduupCF0VZnJQZSUYGDkoZoCjijytQB6GOjv4jwvNFvJOO315d4qMxtHIPsVzmYinIswXApsvgFcTNf4c3yn8fqlVnJo7res7BX1B5wwj1Wf+0x0VSnQmKPQ65LrfWfNov+RO8GDBF26//x7+aK4IDsot/Yv/gLB1eZbJaK6C7f2jlAIJDnpGNpDu+SzV7nn1qXokLX/Vbl1tBEU4/o5E+uVGM29xQULIgnqiv0RMv6kear5t/LKn9yYVC2mRFXmo/ekQ+7mqXcLNTaRC3FCPpdJ86MuOO1+/7W/ENRQrKYIqQlWeZ5eRYov4BJMHyWpBqncPrm6OyESlTpAygtxwN/mx5afyi69snbEoEutYL9nCSAvSFOZKNx33sTN6PEX9X4dj8lBzY5wcuQM0lHF8z2GMObxytmbBYKa/xpPPGdZfcxipNqelltBWECQu4vIuYpbMB1EHhh0UmDuBIIzk3uJgzKeAbb6phxlbKZnqm+WpjAfijSqSJ1MJi64bH0G9+jsxMcpi0bo4ZtwFMqaj64/SVmG0HGXiBT0qquBha3ig==
  template:
    metadata:
      name: keycloak-credentials
      namespace: keycloak
    type: Opaque
